services:

  flask_api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URI=mysql+pymysql://flask_user:flask_password@db/flask_db
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
      MYSQL_DATABASE: flask_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge